server:
  applicationConnectors:
    - type: http
      port: 9000

database:
  driverClass: org.h2.Driver
  user: root
  password: root
  url: jdbc:h2:mem:testdb
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create
